// client/pages/Recommendations.tsx
import Navbar from "@/components/Navbar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Sparkles,
  Target,
  BookOpen,
  Users,
  TrendingUp,
  Brain,
  Zap,
  Star,
} from "lucide-react";
import { Link } from "react-router-dom";

export default function Recommendations() {
  return (
    <div className="min-h-screen bg-background">
      <Navbar />

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="text-center mb-12">
          <Badge variant="outline" className="mb-4">
            <Sparkles className="w-3 h-3 mr-1" />
            AI-Powered
          </Badge>
          <h1 className="text-3xl md:text-4xl font-bold mb-4">
            Personalized Recommendations
          </h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Get AI-powered recommendations for skills, courses, and coaches
            based on your goals and learning style
          </p>
        </div>

        {/* Coming Soon */}
        <Card className="text-center py-20">
          <CardContent>
            <div className="w-20 h-20 bg-gradient-to-br from-primary to-accent rounded-full flex items-center justify-center mx-auto mb-6">
              <Brain className="w-10 h-10 text-white" />
            </div>
            <h2 className="text-3xl font-bold mb-4">AI Recommendations</h2>
            <p className="text-lg text-muted-foreground mb-8 max-w-2xl mx-auto">
              Our advanced AI system will analyze your goals, preferences, and
              learning patterns to provide personalized recommendations.
            </p>

            <div className="grid md:grid-cols-3 gap-6 max-w-4xl mx-auto mb-12">
              <Card className="p-6 border-primary/20">
                <div className="w-12 h-12 bg-primary/10 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Target className="w-6 h-6 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">Smart Goal Setting</h3>
                <p className="text-sm text-muted-foreground">
                  AI helps you define clear, achievable goals based on your
                  interests and career aspirations
                </p>
              </Card>

              <Card className="p-6 border-accent/20">
                <div className="w-12 h-12 bg-accent/10 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <BookOpen className="w-6 h-6 text-accent" />
                </div>
                <h3 className="font-semibold mb-2">Course Recommendations</h3>
                <p className="text-sm text-muted-foreground">
                  Discover courses and skills that align with your career path
                  and learning preferences
                </p>
              </Card>

              <Card className="p-6 border-info/20">
                <div className="w-12 h-12 bg-info/10 rounded-lg flex items-center justify-center mx-auto mb-4">
                  <Users className="w-6 h-6 text-info" />
                </div>
                <h3 className="font-semibold mb-2">Coach Matching</h3>
                <p className="text-sm text-muted-foreground">
                  Find coaches whose expertise and teaching style perfectly
                  match your learning needs
                </p>
              </Card>
            </div>

            <div className="space-y-4">
              <h3 className="text-lg font-semibold">Coming Features:</h3>
              <div className="grid md:grid-cols-2 gap-4 max-w-2xl mx-auto text-sm text-muted-foreground">
                <div className="flex items-center">
                  <Zap className="w-4 h-4 mr-2 text-warning" />
                  Skill gap analysis
                </div>
                <div className="flex items-center">
                  <TrendingUp className="w-4 h-4 mr-2 text-success" />
                  Career progression paths
                </div>
                <div className="flex items-center">
                  <Star className="w-4 h-4 mr-2 text-primary" />
                  Learning style assessment
                </div>
                <div className="flex items-center">
                  <Brain className="w-4 h-4 mr-2 text-accent" />
                  Personalized learning plans
                </div>
              </div>
            </div>

            <div className="mt-8">
              <Button asChild>
                <Link to="/coaches">Browse Coaches Instead</Link>
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// nuxt-coach-connect/pages/recommendations.vue
<template>
  <div class="recommendations">
    <div class="container">
      <div class="recommendations__header">
        <div class="badge badge--primary">
          <Icon name="sparkles" :size="12" />
          AI-Powered
        </div>
        <h1 class="recommendations__title">
          Personalized Recommendations
        </h1>
        <p class="recommendations__description">
          Get AI-powered recommendations for skills, courses, and coaches
          based on your goals and learning style
        </p>
      </div>

      <!-- Coming Soon -->
      <div class="card text-center recommendations__coming-soon">
        <div class="recommendations__icon">
          <Icon name="brain" :size="40" />
        </div>
        <h2 class="recommendations__coming-title">AI Recommendations</h2>
        <p class="recommendations__coming-description">
          Our advanced AI system will analyze your goals, preferences, and
          learning patterns to provide personalized recommendations.
        </p>

        <div class="recommendations__features">
          <div class="feature-card">
            <div class="feature-card__icon">
              <Icon name="target" :size="24" />
            </div>
            <h3 class="feature-card__title">Smart Goal Setting</h3>
            <p class="feature-card__description">
              AI helps you define clear, achievable goals based on your
              interests and career aspirations
            </p>
          </div>

          <div class="feature-card">
            <div class="feature-card__icon">
              <Icon name="book-open" :size="24" />
            </div>
            <h3 class="feature-card__title">Course Recommendations</h3>
            <p class="feature-card__description">
              Discover courses and skills that align with your career path
              and learning preferences
            </p>
          </div>

          <div class="feature-card">
            <div class="feature-card__icon">
              <Icon name="users" :size="24" />
            </div>
            <h3 class="feature-card__title">Coach Matching</h3>
            <p class="feature-card__description">
              Find coaches whose expertise and teaching style perfectly
              match your learning needs
            </p>
          </div>
        </div>

        <div class="coming-features">
          <h3 class="coming-features__title">Coming Features:</h3>
          <div class="coming-features__grid">
            <div class="coming-feature">
              <Icon name="zap" :size="16" />
              Skill gap analysis
            </div>
            <div class="coming-feature">
              <Icon name="trending-up" :size="16" />
              Career progression paths
            </div>
            <div class="coming-feature">
              <Icon name="star" :size="16" />
              Learning style assessment
            </div>
            <div class="coming-feature">
              <Icon name="brain" :size="16" />
              Personalized learning plans
            </div>
          </div>
        </div>

        <NuxtLink to="/coaches" class="btn btn--primary">
          Browse Coaches Instead
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup>
useHead({
  title: 'AI Recommendations - CoachConnect',
  meta: [
    { name: 'description', content: 'Get AI-powered recommendations for skills, courses, and coaches based on your goals and learning style' }
  ]
})
</script>

<style lang="scss" scoped>
.recommendations {
  min-height: 100vh;
  padding: 2rem 0;

  &__header {
    text-align: center;
    margin-bottom: 3rem;
  }

  &__title {
    font-size: 2.5rem;
    font-weight: 700;
    margin: 1rem 0;

    @include respond-to(md) {
      font-size: 3rem;
    }
  }

  &__description {
    font-size: 1.125rem;
    color: $muted-foreground;
    max-width: 32rem;
    margin: 0 auto;
  }

  &__coming-soon {
    padding: 5rem 2rem;
  }

  &__icon {
    width: 5rem;
    height: 5rem;
    background: linear-gradient(135deg, $primary, $accent);
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0 auto 1.5rem;
    color: white;
  }

  &__coming-title {
    font-size: 2rem;
    font-weight: 700;
    margin-bottom: 1rem;
  }

  &__coming-description {
    font-size: 1.125rem;
    color: $muted-foreground;
    max-width: 32rem;
    margin: 0 auto 3rem;
    line-height: 1.6;
  }

  &__features {
    display: grid;
    gap: 1.5rem;
    max-width: 64rem;
    margin: 0 auto 3rem;

    @include respond-to(md) {
      grid-template-columns: repeat(3, 1fr);
    }
  }
}

.feature-card {
  padding: 1.5rem;
  border: 1px solid rgba($primary, 0.2);
  border-radius: 0.75rem;
  text-align: center;

  &__icon {
    width: 3rem;
    height: 3rem;
    background-color: lighten($primary, 40%);
    border-radius: 0.5rem;
    display: flex;
    align-items: center;
    justify-content: center;
    margin: 0 auto 1rem;
    color: $primary;
  }

  &__title {
    font-weight: 600;
    margin-bottom: 0.5rem;
  }

  &__description {
    font-size: 0.875rem;
    color: $muted-foreground;
    line-height: 1.5;
  }
}

.coming-features {
  margin-bottom: 2rem;

  &__title {
    font-size: 1.125rem;
    font-weight: 600;
    margin-bottom: 1rem;
  }

  &__grid {
    display: grid;
    gap: 1rem;
    max-width: 32rem;
    margin: 0 auto;

    @include respond-to(md) {
      grid-template-columns: repeat(2, 1fr);
    }
  }
}

.coming-feature {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.875rem;
  color: $muted-foreground;
}

.badge--primary {
  background-color: $primary;
  color: $primary-foreground;
}
</style>
